### ISSUE TITLE
what about a beacon using module stomping ?

### ISSUE THREAD

**Issue by ghost** [thefLink/Hunt-Sleeping-Beacons#1]
any help for a beacon residing in a module on disk?

**Comment by thefLink** [comment]
In my tests, the tool successfully detected beacons hiding in file backed memory including module stomping

**Comment by thefLink** [comment]
I need to correct myself: modulestomping is a way to bypass the idea of this project.
However, other techniques, such as phantomdllhollowing will be found :)

**Comment by ghost** [comment]
hahahah i confirm, well I'm still testing beacon and its behavior everyday.i have to admit that tweaking existing code is not a bad idea at all.

**Comment by thefLink** [comment]
Updated the code to identify calls to NtDelayExecution from stomped modules :-)

**Comment by ghost** [comment]
Can’t we somehow unhook??? Hahaha
